### PR TITLE
UI: various ui related fixes

### PR DESCRIPTION
**Pull request by mgerhardy**
See issue #79 (No accept button for options that prompt to restart)

### CODE REVIEW

**Comment by kai-li-wop** [comment]
Not quite the expected behavior was achieved yet. When I enter the sound menu for the first time, the Accept button is already shown, even though I have not yet made any changes. If I then switch off "Use OpenAL" for example, the Accept button disappears, so I cannot restart the game. It should be the other way around. If I change an option that requires a restart, the Accept button should then appear so that I can trigger the restart.

Also when I disable and re-enable the voice chat option, there is a line of text explaining that I should restart the game to enable this option. If this is really necessary, the Accept button should be shown instead of this text. I just found that out and apparently overlooked it before.
shot0001

Another side node: Also when disabling OpenAL, the text line below "needs OpenAL & fast network:" starts to blink, which is expected behavior. But the tooltip text of "auto switch song" also is blinking then. Was like this in WoP 1.6 but should not be. But it is just cosmetics.

**Comment by kai-li-wop** [comment]
HW gamma option works like expected.

**Comment by mgerhardy** [comment]
I don't think that a restart is needed to activate voip. But you have to have a rate > 25000 set in order to use it. Maybe we should just change the text. I also managed to get the blinking text overlapping with voip volume controls. There are some bugs in this menu. Will investigate possible fixes asap.

**Comment by kai-li-wop** [comment]
Yes, the message "Restart the game to enable Voice Chat! is not necessary any more due to the Accept button appearing. It can be removed imho.
Yes, voice chat needs a fast network, That's why it cannot be activated, when the user has chosen a rate below LAN/DSL I think. That's why the hint message. It also could be transferred into a tool tip, but not necessary.

**Comment by mgerhardy** [comment]
Message removed and tooltip flashing is fixed, too.

**Review by kai-li-wop — APPROVED** [review]

**Review by kai-li-wop — APPROVED** [review]

**Review by kai-li-wop — APPROVED** [review]

**Review by kai-li-wop — CHANGES_REQUESTED** [review]
When switching off OpenAL and restarting via Accept-Button, the voice chat section is greyed out (which is like expected) but the voice chat option remains shown as enabled. Expected behavior would be, that whenever "fast network" or "OpenAL" is disabled, it must also cause the voice chat option to be disabled and also shown as disabled (off instead of on in the screenshot at position of cursor). Right now, this works like expected only with changing the network option below DSL but not with OpenAL.
shot0000

**Comment by kai-li-wop** [comment]
Another small request that would fit here. Would it be possible to hide the numbers and underscore in the logo selection menu? This is not relevant information for the user and would gain more space between the logo subtitles.
shot0003

**Comment by mgerhardy** [comment]
I don't think we should disable voip, just because we've disabled openal. voip isn't used nor is it available (afaik) when we aren't using openal. But re-activating openal will also just make use of your last set voip configuration value - otherwise you would have to activate voip again if you re-activate openal.

I've removed the numbers and the underscore from logo names.

**Comment by mgerhardy** [comment]
As I've just found out, ioq3 also support sound capturing for SDL >= 2.0.5 - that's why we removed the openal<->voip connection from the ui

**Review by kai-li-wop — APPROVED** [review]
I re-checked all issues connected to this thread and could not reproduce them any more.

**Pull request merged**
