### PR TITLE
Updated to latest ioq3

### PR DESCRIPTION
**Pull request by mgerhardy**
Includes github actions pipelines with downloadable artifacts. I will clean the diff between ioq3 and wop even more.

### CODE REVIEW

**Comment by codemasher** [comment]
Thank you! (for a second i got a bit overexcited that this would be an actual updated ioq3-wop :laughing: ...eyes calendar...)

**Comment by codemasher** [comment]
wait, it is...? i only scrolled over the summary and saw the ioq3 branch update, but... failed to notice that one last commit :D

**Comment by mgerhardy** [comment]
Yes, it is wop rebased to latest ioq3. There were a lot of conflicts that I all had to resolve manually. It works again on macosx and also works fine on linux - windows is untested - but the newly added github actions - that are now part of this project, too - are producing binaries for all three platforms. So if anyone could test windows and report back - please let me know of any issues.

**Comment by mgerhardy** [comment]
One thing where I just added a TODO comment though is the opengl2 renderer - the flag `RF_FORCEENTALPHA` is not handled properly for gl2

**Comment by codemasher** [comment]
Thank you so much! (also happy 14th anniversary, WoP-Standalone!)

Just did a quick check on windows and had the dedicated server crashing with `Bad game system trap: 582` and the client crashes with a `Bad system cgame trap: 90` when trying to start a game via "Create". I'd need a bit more time to set up a clean test environment though. Also, i might aswell just add you to the team over here so that you can push directly.

**Comment by mgerhardy** [comment]
The errors you got is most likely the missing updated qvm files. They should either go to wop/vm/*.qvm or you should create a pk3. This looks like it it using the old 1.6 qvms

**Comment by mgerhardy** [comment]
Getting an error in the ui when I enter the system settings - but the game works fine for me in MP between linux and osx

**Comment by codemasher** [comment]
Ah! So i put the vm files in a `wop_007.pk3` and the client runs fine, the dedicated server however still crashes with the above error. What i've noticed is that the power of jump pads seems reduced (to default q3a?). In Padgarden for example it's impossible to jump to the intended destinations. Also i think that there should be a hard limit for `com_maxfps` as the 64-bit engine in combination with today's GPUs can lead to unplayable situations (permanent disconnects > 1000fps).

**Comment by mgerhardy** [comment]
UI is fixed - wopded is working for me... weird.
couldn't find anything about the jumppad....

**Comment by codemasher** [comment]
Ok, some observations: 

- i still have no idea about the jump pad power; between 3 different builds it ranged between "way too low", "almost" and "intended".
- i don't know how i was able to circumvent the limit 125 of `com_maxfps` despite the fact it's hard limited via `CG_LimitCvars()`.
- console spam for music files that are unexpected format (... is not 22kHz)
- the bots are fucking hard :laughing: (or am i just too weak??)
- `Bad game system trap: 582` occurs when starting the `server-allgametypes.cfg` and the server tries to load `wop_padasiaCTL`
- the vm files need to be in a `.pk3` otherwise it may cause problems in windows

**Pull request merged**
