### PR TITLE
ALL: version 1.7

### PR DESCRIPTION
**Pull request by mgerhardy**
# General

Related wop-data branch: https://github.com/PadWorld-Entertainment/wop-data/tree/1.7

# Freeze Tag

This is merging the freezetag mod of v1.2 into the current code base.

Unlike the previous version which replaced TDM, this does implement the freezetag mode as a dedicated game mode. In order to test the code a little bit without the need to modify the arena file, I've made every team type map also available in the ft game type (as previously freezetag replaced the team game mode, this shouldn't be a problem).

The assets in wop-data still need some work and must be moved to proper locations and maybe even renamed. I've not yet tested this with any modified asset. I've just checked, that the game mechanic works and the bots are trying to unfreeze their team mates (also needs more testing).

- [x] Update arena file with new `ft` type
- [ ] Test bots with the new game mode
- [ ] Test betty light colors
- [x] Help screen and "menu/help/loadinghelp_freezetag";
- [x] Weapon mark shaders are using the snowmark shader now
- [ ] item_freeze entity def?
- [x] Test that late joining players will auto-freeze
- [ ] check the `FT_DEFAULTWEAPONSET` - might have changed since v1.2
- [ ] Bot chat commands? (https://github.com/PadWorld-Entertainment/worldofpadman/issues/113)
- [ ] Add wallhack icon display behavior to freeze icon
- [ ] Add freeze icon to team overlay, when player is frozen (at position of cartridge icon)

**Update/add assets**

- [x] cgs.media.FreezeScreenShader = trap_R_RegisterShaderNoMip("gfx/screen/ice");
- [ ] ~~cgs.media.thawBarShader = trap_R_RegisterShaderNoMip("hud/thawbar");~~
- [x] cgs.media.freezeIconShader = trap_R_RegisterShader("icons/FREEZEicon");
- [x] cgs.media.snowMarkShader = trap_R_RegisterShader("gfx/damage/snow_mark");
- [x] cgs.media.thawIcon = trap_R_RegisterShader("icons/thawicon");
- [x] cgs.media.iceblockModel = trap_R_RegisterModel("models/iceblock");

# Assets

Updated asset paths

### CODE REVIEW

**Comment by mgerhardy** [comment]
Reminder for myself: https://github.com/PadWorld-Entertainment/worldofpadman/pull/131 still has a report for the settings menu which is not yet done.

**Comment by kai-li-wop** [comment]
I guess I can close #93 then.

**Comment by kai-li-wop** [comment]
I tested the freeze tag icon and it is shown as above head icon instead the teammate logo, like expected. I also could see the related option added to the ui menu code, but the entry is still not shown in the menu. Is there something still missing or did I missed something?

**Comment by mgerhardy** [comment]
should be fixed now

**Comment by kai-li-wop** [comment]
@mgerhardy: I just noticed that in Freezetag the icons of the frozen players are visible through walls from a certain proximity, but very small and hardly noticeable. They are supposed to be displayed in the same way as the other marker icons of Healthstation, LPS-Arrow, Balloon-Box and so on. There the size changes dynamically with the distance. I think that the code for this is still missing, since the old Freezetag code was written when these marker icons did not yet exist in WoP.
shot0001

Also, when I was frozen randomly with the boaster in my hand, I was able to continue shooting with it. Well, not really shoot, since I couldn't do any damage and the ammo gauge wasn't counting down either. The water jet, however, continued to animate when pressing the attack button.
shot0009

Also, could we indicate in team overlay, if a teammate is frozen? The freeze icon could be added at position of cartridge icon, shown in syc modes.
shot0001

Updated the ToDo list.

**Comment by mgerhardy** [comment]
[freeze151bsrc.zip](https://github.com/PadWorld-Entertainment/worldofpadman/files/7508396/freeze151bsrc.zip)

**Pull request merged**
