### PR TITLE
UI: Player menu should use WoPascii, not bigchars

### LINKED ISSUE #41: UI: Player menu should use WoPascii, not bigchars
It looks like, but it is not for sure, the Player menu still uses bigchars instead of high res WoPascii font texture (below the 3d model). We should make sure, that WoPascii is used everywhere in the game.

shot0000

### LINKED ISSUE #84: UI: Player menu should use WoPascii, not bigchars
It looks like, but it is not for sure, the Player menu still uses bigchars instead of high res WoPascii font texture (below the 3d model). We should make sure, that WoPascii is used everywhere in the game.

shot0000

### PR DESCRIPTION
**Pull request by mgerhardy**
bigchars was only used as a fallback. As long as WoPascii is found, it should be used now - on all hardware types.

So this basically just simplifies the code a little bit - but shouldn't change the already existing behaviour. WoPascii was chosen for all modern (modern in the sense of modern in 2002) hardware anyway.

Closes #84

### CODE REVIEW

**Review by kai-li-wop — CHANGES_REQUESTED** [review]
The problem is still there. I removed the character sets from the WoPascii and bigchars image files as a test and, as expected, no more characters are displayed anywhere except in the player menu, in the model name display. Whatever is used there, it is not WoPascii and also not bigchars.
shot0000

**Comment by kai-li-wop** [comment]
OK, I found it. There are other font images in menu/art/ folder like font1_prop.tga, font1_prop_glo.tga and font2_prop.tga and registered in ui_qmenu.c. The latter even provides a colored font. These images have never been updated since the PadMod anno 2004 and I don't know where exactly they are still used. So we need to identify exactly where ... probably still in the player menu and and the server connection screen. I think most of it is a leftover from the old PadMod menu. We should switch to WoPascii throughout here and remove the other font images.

**Comment by kai-li-wop** [comment]
Like I assumed, it is also used for the server connection screen while downloading content.
shot0000

**Comment by kai-li-wop** [comment]
Added a better quality menu font texture with https://github.com/PadWorld-Entertainment/wop-data/commit/1096130895d8cb7e02173457fa195d9044396fdc into gfx/2d/fontmenu.png.

**Comment by kai-li-wop** [comment]
Is it possible to check from where this font (TEAM) is loaded? WoPascii or font1_prop?
shot0000

**Comment by mgerhardy** [comment]
`font1_prop` is used there.

The original issue was about `PlayerSettings_Draw`. `font1_prop` is used for everything that is printed via `UI_DrawProportionalString`

**Comment by kai-li-wop** [comment]
Ok, I just wanted to make sure where font1_prop is exactly used. I uploaded a higher resolution version of the font bitmap here: gfx/2d/fontmenu.png. The issue was about very low resolution font in the player menu. As it turns out, that bigchars was not used, we need to replace font1_prop by the new version wherever it is used. Should be only in the player menu, the ingame menu and the server connection screen afaik. When this is done, we can merge this pr.

**Comment by mgerhardy** [comment]
I wonder whether we should merge it already as is, as the other change will make the binaries incompatible to the existing pk3 files - and the users don't have access to the new pk3s. Meaning they can't test the binaries from `main` branch anymore.

And once this is merged, I will just open another PR for the remaining issue of the new texture dimensions. We can merge that once change as late as possible then.

**Review by kai-li-wop — APPROVED** [review]
I could not find any issues with the code changes so far. Apart from having seen some Q3 team name definitions removed. But somewhere team names should be defined as "Red Pads" and "Blue Noses", something like this.

If you want to go for a merge, I am fine with it. Create another PR and add the new font shortly before we start the beta tests to avoid breaking compatibility with the old pk3 files. But as I said already, I think there is no need to wait as we will start official beta test very soon I think. Depends a little on finding a solution for issue #27.

**Pull request merged**
