### PR TITLE
UI: added basic cl_voipSendTarget support to the ui

### PR DESCRIPTION
**Pull request by mgerhardy**
Bildschirmfoto von 2021-09-14 22-11-45 (don't mind the dark look - there was an overlay of my windowmanager active at that time)

Bildschirmfoto von 2021-09-14 22-14-05

See https://github.com/PadWorld-Entertainment/worldofpadman/discussions/138

### CODE REVIEW

**Comment by mgerhardy** [comment]
That cvar allows a lot more combinations of what we expose via ui with this PR - but it's imo better than nothing at the moment.

We should maybe still disable the ui change if none of the pre-defined values matches the current value.

**Comment by mgerhardy** [comment]
This is already part of the in-game menu - and also with a lot more details.

**Comment by kai-li-wop** [comment]
I think to have this option also in the sound setup menu is really handy. I vote for an implementation into the UI even if it is already adjustable via the ingame menu. I also found out, that the ingame menu provides only 'all' and 'team' options in the drop down. 'team' is not in your list and 'none', 'attacker', 'spatial' and 'crosshair' are missing. I guess the voip options need a bigger overhaul.

**Comment by kai-li-wop** [comment]
This will be implemented with [#143](https://github.com/PadWorld-Entertainment/worldofpadman/issues/143) of the new repo.

**Pull request closed without merging**
