### PR TITLE
LINUX: added xdg support

### PR DESCRIPTION
**Pull request by mgerhardy**
Upstream MR: https://github.com/ioquake/ioq3/pull/498

### CODE REVIEW

**Comment by mgerhardy** [comment]
Updated PR regarding the comments from ioq3 upstream.

**Comment by robo9k** [comment]
Does this need its own pull request in this repo here or is it to discuss additional concerns if we don't merge that as-is?

I second the upstream backwards compatibility concerns - if this breaks user installations we're back to fec64ae180c71175948e15d67135353e60bf9c8c
I don't consider it enough to have e.g. a migration script as part of our distributed files, since this'll have to be correctly applied by all sorts of downstreams such as Linux distros. Unless we make a breaking change with matching major version number, the game has to remain compatible.
One solution could be to add the XDG directory as an additional VFS path instead of replacing `homePath`

**Comment by robo9k** [comment]
Now for the more pedantic part, this does not actually follow [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
>  The XDG Base Directory Specification is based on the following concepts:
> * There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable `$XDG_DATA_HOME`.
> * There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable `$XDG_CONFIG_HOME`.
> * There is a set of preference ordered base directories relative to which data files should be searched. This set of directories is defined by the environment variable `$XDG_DATA_DIRS`.
> * There is a set of preference ordered base directories relative to which configuration files should be searched. This set of directories is defined by the environment variable `$XDG_CONFIG_DIRS`.
> * There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable `$XDG_CACHE_HOME`.
> * There is a single base directory relative to which user-specific runtime files and other file objects should be placed. This directory is defined by the environment variable `$XDG_RUNTIME_DIR`. 

I'll note that the spec says *should* unlike *must* in other places. It then goes on to describe what kind of files are expected to be written in which directory and further constraints such as directory permissions.

With this merge request, the engine will write/read all kinds of files into/from `XDG_DATA_HOME`, even auto-generated configuration files and auto-downloaded and thus cache as well as log files.
I'm aware that the Quake 3 engine and VFS was never written with those distinctions in mind. I still think that using a subset of the XDG spec is better than nothing - but I'd expect a remark in the user documentation, which is entirely absent in this merge request.

**Comment by mgerhardy** [comment]
True - it does not follow the guidelines 100% - but it already puts most of the data into the location the user would expect. We should maybe not merge this for 1.6.1 - but we should for any future version imo. As the user is expecting the data in that position and not in the root of the home dir.

**Pull request closed without merging**
