### PR TITLE
ALL: Mission pack and dead code removal

### PR DESCRIPTION
**Pull request by mgerhardy**
further code cleanup by removing unused mission pack, singleplayer and ui code.

Also removed support for non standalone games and removed legacy protocol support

### CODE REVIEW

**Comment by codemasher** [comment]
Like the whitespace removal i'm not sure about this one, except this one will haunt anyone who might pick up the code in a couple years, trying to update the codebase.

**Comment by kai-li-wop** [comment]
I follow here the opinion that the future changes in ioquake3 will remain manageable and therefore only single fixes or components have to be taken over in WoP in the future. The effort will remain low. In this respect, it is OK in my view to remove superfluous code and whitespaces. I am for it.

**Comment by codemasher** [comment]
There is no gain in removing the missionpack code and making the WoP codebase widely incompatible to upstream merges, I don't see any benefit here. (and yes, i had this idea before and it didn't take long to see how bad it was)

**Comment by mgerhardy** [comment]
There are other q3 code bases that are no longer compatible to the ioq3 code. And if we continue to work on the game (what I'm planning to do) - we should improve the code base, clean it up, modernize it, automate a lot of things (like unittesting, packaging, maybe change the build system to no longer maintain msvc and xcode) - this will break compatibility with upstream anyway.

See e.g. https://github.com/etlegacy/etlegacy

**Comment by codemasher** [comment]
Right now we're still in the range of "mostly compatible" and changing this just because "others are incompatible too" is a very poor argument. Nothing stops you from updating other things while just completely ignoring the missionpack code for the sake of being update friendly?

**Comment by mgerhardy** [comment]
It's just time consuming to keep it in - navigating the code is harder - maintaining it is harder, because I would have to keep stuff compatible, have to read dead and unused code for theoretically future updates from upstream that can be done anyway. And I not only used on argument like "others did it, too" - I also added the argument, that I plan to modernize and clean up the code base as well as the build system. This is something I plan to do, as I can't waste my time in maintaining msvc and xcode stuff. Don't want to waste my time in reading and maintaining dead code. Feel free to create a tag or whatever to keep the last compatible commit to ioq3 - I also got the reformat branch merged - this is the next step. So maintaining the mission pack code to be able to make merges easier is also not a valid argument after the reformat.

**Comment by mgerhardy** [comment]
One last point - about the merge advantages. It is a lot easier to interact with all the different q3 code styles if you can copy parts over, apply your code formatter and see the changes in the diff. Pick the relevant parts with the patch feature of git. It is really hard to merge in fixes from more up-to-date engines due to all the whitespace changes. So even this is just about time resp. time wasting.

**Review by kai-li-wop — APPROVED** [review]

**Pull request merged**
