### PR TITLE
BUILD: added libtheora

### PR DESCRIPTION
**Pull request by mgerhardy**
This updates the makefile to activate theora or ogm support again (the intro is in ogm format and this change was forgotten in the rebase of ioq3)

Needed for 1.6.1 for the sequences.

### CODE REVIEW

**Review by kai-li-wop — APPROVED** [review]
I cannot really judge the code but as @mgerhardy already implemented this before and working as it should, I would give it a go.

**Comment by codemasher** [comment]
What was weird in the other (messy) branch, is that after the addition somehow the build resulted in weird dependencies and resulted in a crash, namely, the windows mingw64 build was suddenly linked against the SDL2.dll instead of SDL264.dll, which could have been totally unrelated, however only happened with libtheora enabled. It doesn't happen now.

**Comment by mgerhardy** [comment]
Could it be merged?

**Comment by codemasher** [comment]
I've only done a quick check so far to see whether it still crashes and it didn't. So mark this one as things to look for if anything goes wrong.

**Pull request merged**
