### PR TITLE
JANITORIAL: various cleanups

### PR DESCRIPTION
**Pull request by mgerhardy**
Looks like we don't want to have the dylib, dll or so for the different platforms - but only the qvms

Also removed the trailing whitespaces in all files in a single commit to keep future diffs as small as possible

The whitespace commit is also a PR in ioq3 (https://github.com/ioquake/ioq3/pull/495)

### CODE REVIEW

**Comment by codemasher** [comment]
I once thought removing all the trailing whitespace was a great idea, but i think this will haunt us when updating from upstream.

**Comment by robo9k** [comment]
I second not changing bundled thirdparty code. If it's already upstreamed in ioq3 however it should be fine, it's unlikely we'll have widely different versions.

**Comment by mgerhardy** [comment]
My arguments for this and the PR upstream are basically the same. My IDE tidies up after me - and currently I can't use these features because it will create a very huge diff each time I save the editor. It feels dirty to not do it. Also merging with upstream is no problem - single commits are cherry-picked anyway - and using `git am` with trailing whitespaces removed is also no problem.

**Comment by robo9k** [comment]
Not sure I agree with the `BUILD_GAME_SO` change. In general the ioq3 internal QVM toolchain doesn't emit that many warnings and - assuming we care for those - not having the usually high quality warnings from GCC/Clang reduces code quality.
We do not want to ship the built shared game libraries, but that doesn't mean we should never build them.

**Comment by mgerhardy** [comment]
That is a good point. Should we keep it as default activated and only disable it in the pipeline (to not include it in the packages we are producing?)

**Comment by mgerhardy** [comment]
I've removed the qvm/so commit - so only whitespace changes are left.

**Comment by robo9k** [comment]
I've skimmed the diff and didn't see anything problematic - so looks good to merge for me 👍 
Note however that upstream closed the request without merging - so @codemasher 's remarks might still hold

**Comment by mgerhardy** [comment]
What about this change now? Should I merge it? It starts to annoy me to always perform `git add -p` over small changes due to whitespace changes ;)

**Comment by codemasher** [comment]
Honestly i don't care as it will haunt YOU ;)

**Comment by codemasher** [comment]
Also not that this change is still against "master", needs a cherry pick then.

**Pull request merged**
